/* VELORA — independent interactions */

'use strict';
const $ = (selector, scope=document) => scope.querySelector(selector);
const $$ = (selector, scope=document) => [...scope.querySelectorAll(selector)];
const menuButton = $('.nav-toggle');
const menu = $('#site-nav');
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close navigation':'Open navigation');menu.classList.toggle('is-open',open);});
$$('#site-nav a').forEach(a=>a.addEventListener('click',()=>{menu?.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false');}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu?.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false');}});
const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reducedMotion && 'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('reveal');observer.unobserve(entry.target);}}),{threshold:.09});$$('[data-reveal]').forEach(el=>observer.observe(el));}
$$('input[type="date"]').forEach(el=>{const now=new Date();el.min=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');});
$$('.demo-form').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);const result=$('.form-result',form);result.textContent='Your demo request is ready, '+data.get('name')+'. '+[...data.entries()].filter(([key])=>!['name','email'].includes(key)).map(([,value])=>value).filter(Boolean).join(' · ')+'. This is a preview only; no request has been sent.';result.focus();}));
function showDialog(title,html){let dialog=$('#detail-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='detail-dialog';dialog.className='dialog';dialog.setAttribute('aria-labelledby','dialog-title');document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog){const box=dialog.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)dialog.close();}});}dialog.innerHTML='<button class="dialog-close" aria-label="Close details">Close ×</button><h2 id="dialog-title"></h2><div class="dialog-content"></div>';$('#dialog-title',dialog).textContent=title;$('.dialog-content',dialog).innerHTML=html;$('.dialog-close',dialog).addEventListener('click',()=>dialog.close());dialog.showModal();}
$$('[data-detail]').forEach(button=>button.addEventListener('click',()=>{const content=document.getElementById(button.dataset.detail);if(content)showDialog(button.dataset.title||button.textContent.trim(),content.innerHTML);}));
$$('[data-filter-group]').forEach(group=>{const scope=document.getElementById(group.dataset.filterGroup);$$('[data-filter]',group).forEach(button=>button.addEventListener('click',()=>{$$('[data-filter]',group).forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$$('[data-category]',scope).forEach(item=>item.hidden=button.dataset.filter!=='all'&&!item.dataset.category.split(' ').includes(button.dataset.filter));}));});


const rituals={face:[['The Dew Facial','A gentle, personalized skin ritual with cleansing, thoughtful touch and a little room to glow.','60 min','$120'],['The Sculpt & Soothe','A slower facial ritual with massage and textures chosen for your skin’s comfort.','75 min','$145'],['The Little Refresh','A focused moment of care when a little time is all you have.','30 min','$65']],body:[['The Grounding Massage','An unhurried full-body massage, tailored to the pressure and pace that feel right.','60 min','$115'],['The Warm Stone Ritual','Smooth, warmed stones and gentle touch for a deeply restful experience.','90 min','$165'],['The Botanical Polish','A considered body exfoliation followed by nourishing oils and quiet time.','45 min','$90']],mind:[['The Quiet Hour','Breath, stillness, and space to step out of the pace of the day.','60 min','$75'],['The Garden Pause','Guided gentle movement, herbal tea and a little time in our private garden.','45 min','$55'],['The Evening Exhale','A softly guided relaxation ritual to close the day with intention.','30 min','$45']]};function renderRituals(category){$('#ritual-list').innerHTML=rituals[category].map(([name,desc,time,price],i)=>'<article class="ritual-row"><span>0'+(i+1)+'</span><h3>'+name+'</h3><p>'+desc+'</p><span>'+time+'<br>'+price+'</span><button data-ritual-name="'+name+'" aria-label="Explore '+name+'">↗</button></article>').join('');$$('[data-ritual-name]').forEach(b=>b.addEventListener('click',()=>showDialog(b.dataset.ritualName,'<p>Your therapist begins with a quiet conversation about how you would like to feel, then shapes the experience around your preferences.</p><p>Sample treatment only. No appointment or payment is processed.</p><a class="button" href="#booking">Plan your visit ↗</a>')));}renderRituals('face');$$('[data-ritual]').forEach(b=>b.addEventListener('click',()=>{$$('[data-ritual]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderRituals(b.dataset.ritual);}));$$('[data-package]').forEach(b=>b.addEventListener('click',()=>{$('select[name="ritual"]').value=b.dataset.package;$('#booking').scrollIntoView({behavior:reducedMotion?'auto':'smooth'});}));

document.addEventListener('click',event=>{const anchor=event.target.closest('dialog a[href^="#"]');if(anchor)anchor.closest('dialog').close();});
