/* AZURE COVE — independent interactions */

'use strict';
const $ = (selector, scope=document) => scope.querySelector(selector);
const $$ = (selector, scope=document) => [...scope.querySelectorAll(selector)];
const menuButton = $('.nav-toggle');
const menu = $('#site-nav');
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close navigation':'Open navigation');menu.classList.toggle('is-open',open);});
$$('#site-nav a').forEach(a=>a.addEventListener('click',()=>{menu?.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false');}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu?.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false');}});
const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reducedMotion && 'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('reveal');observer.unobserve(entry.target);}}),{threshold:.09});$$('[data-reveal]').forEach(el=>observer.observe(el));}
$$('input[type="date"]').forEach(el=>{const now=new Date();el.min=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');});
$$('.demo-form').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);const result=$('.form-result',form);result.textContent='Your demo request is ready, '+data.get('name')+'. '+[...data.entries()].filter(([key])=>!['name','email'].includes(key)).map(([,value])=>value).filter(Boolean).join(' · ')+'. This is a preview only; no request has been sent.';result.focus();}));
function showDialog(title,html){let dialog=$('#detail-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='detail-dialog';dialog.className='dialog';dialog.setAttribute('aria-labelledby','dialog-title');document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog){const box=dialog.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)dialog.close();}});}dialog.innerHTML='<button class="dialog-close" aria-label="Close details">Close ×</button><h2 id="dialog-title"></h2><div class="dialog-content"></div>';$('#dialog-title',dialog).textContent=title;$('.dialog-content',dialog).innerHTML=html;$('.dialog-close',dialog).addEventListener('click',()=>dialog.close());dialog.showModal();}
$$('[data-detail]').forEach(button=>button.addEventListener('click',()=>{const content=document.getElementById(button.dataset.detail);if(content)showDialog(button.dataset.title||button.textContent.trim(),content.innerHTML);}));
$$('[data-filter-group]').forEach(group=>{const scope=document.getElementById(group.dataset.filterGroup);$$('[data-filter]',group).forEach(button=>button.addEventListener('click',()=>{$$('[data-filter]',group).forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$$('[data-category]',scope).forEach(item=>item.hidden=button.dataset.filter!=='all'&&!item.dataset.category.split(' ').includes(button.dataset.filter));}));});


$('#stay-search').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const start=new Date(f.get('arrival')+'T12:00:00'),end=new Date(f.get('departure')+'T12:00:00');if(end<=start){$('#stay-result').textContent='Please choose a departure after your arrival.';return;}const nights=Math.round((end-start)/86400000);$('#stay-result').textContent=nights+' nights for '+f.get('guests')+'. Explore the Lagoon Suite from $680/night or the Garden Residence from $940/night. Sample rates; no live availability is checked.';$('#booking input[name="date"]').value=f.get('arrival');});
$('input[name="arrival"]').addEventListener('change',e=>{const day=new Date(e.target.value+'T12:00:00');day.setDate(day.getDate()+1);$('input[name="departure"]').min=[day.getFullYear(),String(day.getMonth()+1).padStart(2,'0'),String(day.getDate()).padStart(2,'0')].join('-');});
$$('[data-room]').forEach(b=>b.addEventListener('click',()=>showDialog(b.dataset.room,'<p>Quiet natural materials, generous indoor-outdoor spaces, an ocean-inspired bathroom and thoughtful island touches.</p><p>Included: daily breakfast, island host, snorkeling equipment and return shared boat transfers from the seaplane platform.</p><a class="button" href="#booking">Imagine your stay ↗</a>')));const experiences={'Beneath the blue':'Explore the house reef with a marine guide. Small groups, unhurried swims and a closer look at the life beneath the surface.','The art of slowing down':'A garden spa ritual, gentle movement at sunrise and time to do a little less. Treatments are tailored around how you want to feel.','Sail into the sunset':'Step aboard our island dhoni for a quiet evening on the water, with a small picnic and a front-row seat to the changing sky.'};$$('[data-experience]').forEach(b=>b.addEventListener('click',()=>showDialog(b.dataset.experience,'<p>'+experiences[b.dataset.experience]+'</p>')));

document.addEventListener('click',event=>{const anchor=event.target.closest('dialog a[href^="#"]');if(anchor)anchor.closest('dialog').close();});
