/* ATELIER NOIR — independent interactions */

'use strict';
const $ = (selector, scope=document) => scope.querySelector(selector);
const $$ = (selector, scope=document) => [...scope.querySelectorAll(selector)];
const menuButton = $('.nav-toggle');
const menu = $('#site-nav');
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close navigation':'Open navigation');menu.classList.toggle('is-open',open);});
$$('#site-nav a').forEach(a=>a.addEventListener('click',()=>{menu?.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false');}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu?.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false');}});
const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reducedMotion && 'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('reveal');observer.unobserve(entry.target);}}),{threshold:.09});$$('[data-reveal]').forEach(el=>observer.observe(el));}
$$('input[type="date"]').forEach(el=>{const now=new Date();el.min=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');});
$$('.demo-form').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);const result=$('.form-result',form);result.textContent='Your demo request is ready, '+data.get('name')+'. '+[...data.entries()].filter(([key])=>!['name','email'].includes(key)).map(([,value])=>value).filter(Boolean).join(' · ')+'. This is a preview only; no request has been sent.';result.focus();}));
function showDialog(title,html){let dialog=$('#detail-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='detail-dialog';dialog.className='dialog';dialog.setAttribute('aria-labelledby','dialog-title');document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog){const box=dialog.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)dialog.close();}});}dialog.innerHTML='<button class="dialog-close" aria-label="Close details">Close ×</button><h2 id="dialog-title"></h2><div class="dialog-content"></div>';$('#dialog-title',dialog).textContent=title;$('.dialog-content',dialog).innerHTML=html;$('.dialog-close',dialog).addEventListener('click',()=>dialog.close());dialog.showModal();}
$$('[data-detail]').forEach(button=>button.addEventListener('click',()=>{const content=document.getElementById(button.dataset.detail);if(content)showDialog(button.dataset.title||button.textContent.trim(),content.innerHTML);}));
$$('[data-filter-group]').forEach(group=>{const scope=document.getElementById(group.dataset.filterGroup);$$('[data-filter]',group).forEach(button=>button.addEventListener('click',()=>{$$('[data-filter]',group).forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$$('[data-category]',scope).forEach(item=>item.hidden=button.dataset.filter!=='all'&&!item.dataset.category.split(' ').includes(button.dataset.filter));}));});


const wishlist=new Set();$$('[data-wish]').forEach(b=>b.addEventListener('click',()=>{const title=b.dataset.wish;if(wishlist.has(title))wishlist.delete(title);else wishlist.add(title);b.setAttribute('aria-pressed',String(wishlist.has(title)));b.textContent=wishlist.has(title)?'✓':'+';$('#wish-count').textContent=wishlist.size;}));$('#wishlist-button').addEventListener('click',()=>showDialog('Your considered pieces',wishlist.size?'<p>'+[...wishlist].join('</p><p>')+'</p><p>Saved for this visit. This concept does not process orders.</p>':'<p>Your wishlist is waiting. Use the + on a piece to keep it close.</p>'));
const pieces=[['The Column Coat','420','Warm sand','A long, considered silhouette with a soft shoulder and a clean, uninterrupted line.'],['The Sculpted Knit','185','Ink black','A soft structure, a considered neckline, and room to move.'],['The Fluid Trouser','210','Stone','An easy drape, a generous leg and a tailored finish.'],['The Form Top','125','Soft ivory','A quiet foundation for an expressive wardrobe.']];$$('[data-product]').forEach(b=>b.addEventListener('click',()=>{const [title,price,color,desc]=pieces[Number(b.dataset.product)];showDialog(title,'<p>'+color+' · $'+price+'</p><p>'+desc+'</p><label>Explore a size<select><option>XS</option><option>S</option><option>M</option><option>L</option><option>XL</option></select></label><p>Illustrative editorial imagery. This collection is a fictional concept; no purchase is processed.</p>');}));$('#fashion-newsletter').addEventListener('submit',e=>{e.preventDefault();$('#newsletter-result').textContent='Thank you. Your email is valid — this demo has not subscribed or sent your details.';});

document.addEventListener('click',event=>{const anchor=event.target.closest('dialog a[href^="#"]');if(anchor)anchor.closest('dialog').close();});
