/* HART & CO. — independent interactions */

'use strict';
const $ = (selector, scope=document) => scope.querySelector(selector);
const $$ = (selector, scope=document) => [...scope.querySelectorAll(selector)];
const menuButton = $('.nav-toggle');
const menu = $('#site-nav');
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close navigation':'Open navigation');menu.classList.toggle('is-open',open);});
$$('#site-nav a').forEach(a=>a.addEventListener('click',()=>{menu?.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false');}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu?.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false');}});
const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reducedMotion && 'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('reveal');observer.unobserve(entry.target);}}),{threshold:.09});$$('[data-reveal]').forEach(el=>observer.observe(el));}
$$('input[type="date"]').forEach(el=>{const now=new Date();el.min=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');});
$$('.demo-form').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);const result=$('.form-result',form);result.textContent='Your demo request is ready, '+data.get('name')+'. '+[...data.entries()].filter(([key])=>!['name','email'].includes(key)).map(([,value])=>value).filter(Boolean).join(' · ')+'. This is a preview only; no request has been sent.';result.focus();}));
function showDialog(title,html){let dialog=$('#detail-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='detail-dialog';dialog.className='dialog';dialog.setAttribute('aria-labelledby','dialog-title');document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog){const box=dialog.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)dialog.close();}});}dialog.innerHTML='<button class="dialog-close" aria-label="Close details">Close ×</button><h2 id="dialog-title"></h2><div class="dialog-content"></div>';$('#dialog-title',dialog).textContent=title;$('.dialog-content',dialog).innerHTML=html;$('.dialog-close',dialog).addEventListener('click',()=>dialog.close());dialog.showModal();}
$$('[data-detail]').forEach(button=>button.addEventListener('click',()=>{const content=document.getElementById(button.dataset.detail);if(content)showDialog(button.dataset.title||button.textContent.trim(),content.innerHTML);}));
$$('[data-filter-group]').forEach(group=>{const scope=document.getElementById(group.dataset.filterGroup);$$('[data-filter]',group).forEach(button=>button.addEventListener('click',()=>{$$('[data-filter]',group).forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$$('[data-category]',scope).forEach(item=>item.hidden=button.dataset.filter!=='all'&&!item.dataset.category.split(' ').includes(button.dataset.filter));}));});


const practices=[['Business & Corporate','We work with founders, leadership teams and established businesses, bringing a practical understanding of commercial priorities to each conversation.'],['Property & Development','We help clients understand the moving parts of property matters, coordinating closely with their wider professional team.'],['Private Client','We take time to understand family priorities and long-term intentions, supporting thoughtful decisions with clear, considered advice.'],['Dispute Resolution','We begin with the full picture, assess options carefully and help clients understand a practical path forward.']];$$('[data-practice]').forEach(b=>b.addEventListener('click',()=>{const [title,desc]=practices[Number(b.dataset.practice)];$('select[name="practice"]').value=title;showDialog(title,'<p>'+desc+'</p><p>This fictional firm provides a design demonstration, not legal services or advice.</p><a class="button" href="#consultation">Begin a conversation ↗</a>');}));const attorneys=[['Eleanor Hart','Managing Partner','Eleanor brings a measured perspective to complex business decisions, with a particular interest in long-term client relationships.'],['James Caldwell','Partner, Property & Development','James works closely with clients and their wider teams to keep practical priorities at the center of property matters.'],['Sofia Rahman','Partner, Private Client & Disputes','Sofia is known for careful listening, clear communication and a considered approach to sensitive conversations.']];$$('[data-attorney]').forEach(b=>b.addEventListener('click',()=>{const [name,role,bio]=attorneys[Number(b.dataset.attorney)];showDialog(name,'<p>'+role+'</p><p>'+bio+'</p><p>Fictional attorney profile created for this website concept.</p>');}));$$('[data-insight]').forEach(b=>b.addEventListener('click',()=>{const article=b.closest('article');showDialog($('h3',article).textContent,'<p>'+$('p',article).textContent+'</p><p>Thoughtful professional relationships depend on understanding the people, priorities and context behind a question. Our approach begins with listening, then making the next conversation clearer.</p><p>Editorial concept content only; not legal guidance.</p>');}));

document.addEventListener('click',event=>{const anchor=event.target.closest('dialog a[href^="#"]');if(anchor)anchor.closest('dialog').close();});
